version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies"

  build:
    commands:
      - echo "Building Lambda JAR"
      - mvn clean package
      - echo "Packaging SAM application"
      - sam package
        --template-file template.yaml
        --s3-bucket subhashimageapp-sam-bucket
        --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml
