AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM app for SubhashImageApp Upload Notifications

Globals:
  Function:
    Runtime: java21
    Timeout: 30
    MemorySize: 512

Resources:

  UploadsNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SubhashImageApp-UploadsNotificationFunction
      CodeUri: target/UploadsNotificationLambda-1.0.jar
      Handler: com.subhash.lambda.UploadsNotificationLambda.UploadsNotificationHandler::handleRequest

      # 🔑 REQUIRED for DeploymentPreference
#      AutoPublishAlias: live

      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSNSFullAccess
        - AmazonSQSReadOnlyAccess

      Environment:
        Variables:
          SNS_TOPIC_ARN: arn:aws:sns:us-east-1:277707095064:SubhashImageApp-UploadsNotificationTopic

      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:277707095064:SubhashImageApp-UploadsNotificationQueue
            BatchSize: 5

#      DeploymentPreference:
#        Type: Linear10PercentEvery1Minute
